spring.datasource.url=jdbc:postgresql://aws-0-xx-xxxx.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.uzladhegyirumtuafirc
spring.datasource.password=${DB_PASSWORD} 


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
spring.data.web.pageable.default-page-size=20


app.cookie.secure=true