
spring.application.name=backend


# General Set-up
spring.application.name=backend
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.config.import=optional:application-local.properties

# pagination
spring.data.web.pageable.default-page-size=20
spring.mvc.pathmatch.use-suffix-pattern=false
